version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://prueba_toteat:prueba_toteat@db:5432/prueba_toteat_dev
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  db:
    image: postgres:13
    expose:
      - 5432
    environment:
      - POSTGRES_USER=prueba_toteat
      - POSTGRES_PASSWORD=prueba_toteat
      - POSTGRES_DB=prueba_toteat_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - "./data/:/data"

volumes:
  postgres_data:
